title: Yanfeng Wang's Homepage
page-top-title: Yanfeng Wang
top-section-bg-text: Always on the way
home-subtitle: Yanfeng Wang;|&ensp;王彦峰
copyright-text: '&copy; Yanfeng Wang 2024-2025. All Rights Reserved.'
